# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#build is triggered on any change to the master branch
trigger:
- master

#the pool is the ubuntu image for the Agent to run on
pool:
  vmImage: 'ubuntu-latest'

#different steps that are part of the build pipeline
#these are very basic examples
jobs:
- job: Job1
  steps:
  - script: |
      echo Hello, world !
      echo Testing script build pipeline, adding comment here. OK
    displayName: 'Run a one-line script'
    
- job: Job2
  steps:
  - script: |
      echo Hello, world !
      echo Testing script build pipeline, adding comment here - job2
    displayName: 'Run a one-line script'

#multi line script bring run
- job: Job3
  dependsOn: 
  - Job1
  - Job2
  steps:
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
