# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build the FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build the SecondJob  
- stage: DevDeploy
  jobs:
  - job: DevDeploy Job
    steps:
    - bash: echo Build the DevDeploy Job  
- stage: QADeploy
  jobs:
  - job: QADeploy Job
    steps:
    - bash: echo Build the QADeploy Job  
- stage: ProdDeploy
  jobs:
  - job: ProdDeploy Job
    steps:
    - bash: echo Build the ProdDeploy Job  



