# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build the FirstJob 
    - bash: echo $(Agent.OSArchitecture)
    - bash: echo $(Agent.MachineName)
    - bash: echo $(Build.BuildUri)
    - bash: echo $(Build.Repository.ID)
    - bash: echo $(Environment.Name)
    - bash: echo $(System.CollectionId)
    - bash: echo $(System.StageDisplayName)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
  - job: SecondJob
    steps:
    - bash: echo Build the SecondJob  
# - stage: DevDeploy
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo Build the DevDeploy Job for $(company)
# - stage: QADeploy
#   jobs:
#   - job: QADeployJob
#     steps:
#     - bash: echo Build the QADeploy Job for $(company)
# - stage: ProdDeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - bash: echo Build the ProdDeploy Job for $(company)



